<template>
  <NuxtLink
    id="hacktober"
    class="
      relative
      overflow-hidden
      mt-4
      p-8
      w-full
      max-w-screen-lg
      md:h-48
      flex flex-col
      md:flex-row
      items-center
      justify-center
      md:justify-between
      bg-gradient-to-tr
      from-emerald-600
      to-emerald-300
      rounded-lg
      group
    "
    to="/hacktoberfest"
  >
    <div
      class="
        absolute
        h-100
        w-72
        -top-52
        -left-60
        group-hover:-left-50
        transition-all
        bg-emerald-800
        opacity-70
        transform
        -rotate-40
      "
    />
    <div
      class="
        absolute
        h-100
        w-72
        -top-32
        -left-50
        group-hover:-left-60
        transition-all
        bg-emerald-600
        opacity-70
        transform
        -rotate-40
      "
    />
    <div
      class="
        absolute
        h-100
        w-72
        -top-120
        left-80
        group-hover:-top-100
        transition-all
        bg-emerald-200
        opacity-70
        transform
        -rotate-40
      "
    />
    <div
      class="
        absolute
        h-56
        w-72
        -bottom-32
        group-hover:-bottom-22
        -right-36
        group-hover:-right-26
        transition-all
        bg-emerald-800
        opacity-70
        transform
        -rotate-45
      "
    />
    <div class="relative">
      <h1 class="text-4xl sm:text-5xl md:text-6xl">
        Hacktoberfest
      </h1>
    </div>
    <button class="relative px-6 py-3 mt-2 md:mt-0 rounded-lg bg-white text-emerald-600">
      Announcement 🥇
    </button>
  </NuxtLink>
</template>
